# Generated by Django 5.1 on 2024-08-13 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="car_makes/logos/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Car Make",
                "verbose_name_plural": "Car Makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEDAN", "Sedan"),
                            ("SUV", "SUV"),
                            ("WAGON", "Wagon"),
                            ("COUPE", "Coupe"),
                            ("CONVERTIBLE", "Convertible"),
                            ("HATCHBACK", "Hatchback"),
                            ("TRUCK", "Truck"),
                            ("VAN", "Van"),
                        ],
                        default="SUV",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MaxValueValidator(2023),
                            django.core.validators.MinValueValidator(2015),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_electric", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="car_models/photos/"
                    ),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangoapp.carmake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Model",
                "verbose_name_plural": "Car Models",
                "ordering": ["name"],
            },
        ),
    ]
