name: 'Lint and Format Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_python:
    name: Lint and Format Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Run Formatter and Linter
      run: |
        black .  # Automatically formats the code
        flake8 . # Runs the linter after formatting

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Auto-format code"
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git ${{ github.ref }}

  lint_js:
    name: Lint and Format JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Prettier
      run: npm install prettier --global

    - name: Run Formatter
      run: |
        prettier --write "**/*.js"  # Automatically formats the code

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Auto-format JS code"
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git ${{ github.ref }}
